"""
XAI Counterfactual Explanations Dashboard
Assignment A+B — JM0110 Interactive & Explainable AI Design

Run with:
    streamlit run app.py
"""

import json
import os
import random
import time
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st

import data_utils as du

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="XAI CF Explorer",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)

CIFAR_LABEL_NAMES = {v: k for k, v in du.CIFAR_LABELS.items()}  # name→id
CIFAR_LABELS = du.CIFAR_LABELS  # id→name

# ── Persistent guess-mode log ─────────────────────────────────────────────────
GUESSES_FILE = Path(__file__).parent / "guess_log.json"

def load_guesses() -> list:
    if GUESSES_FILE.exists():
        with open(GUESSES_FILE) as f:
            return json.load(f)
    return []

def save_guess(entry: dict):
    guesses = load_guesses()
    guesses.append(entry)
    with open(GUESSES_FILE, "w") as f:
        json.dump(guesses, f, indent=2)


# ── Sidebar navigation ────────────────────────────────────────────────────────
st.sidebar.title("XAI CF Explorer")
st.sidebar.markdown("*Counterfactual Explanation Dashboard*")
page = st.sidebar.radio(
    "Navigate",
    ["Overview", "Image Browser", "Tension Cases", "Guess Mode", "Study Results"],
    index=0,
)

@st.cache_data
def get_df():
    return du.load_results()

df = get_df()


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: Overview
# ═════════════════════════════════════════════════════════════════════════════
if page == "Overview":
    st.title("Counterfactual Explanations — Overview")
    st.markdown(
        """
        This dashboard explores **counterfactual (CF) explanations** generated by 5 different methods
        on MNIST and CIFAR-10 datasets.
        The core research question:
        > *Do objective evaluation metrics (validity, plausibility) align with how users perceive CF explanations?*
        """
    )

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total CFs", f"{len(df):,}")
    col2.metric("Instances (MNIST)", df[df.network == "mnist_output_100"]["image"].nunique())
    col3.metric("Instances (CIFAR)", df[df.network == "cifar_resnet8_output"]["image"].nunique())
    col4.metric("Methods", df["method"].nunique())

    st.subheader("Validity rate by method & dataset")
    validity = (
        df.groupby(["network", "method"])["correctness"]
        .mean()
        .reset_index()
        .rename(columns={"correctness": "validity_rate", "network": "Dataset", "method": "Method"})
    )
    validity["Dataset"] = validity["Dataset"].map(
        {"mnist_output_100": "MNIST", "cifar_resnet8_output": "CIFAR-10"}
    )
    validity["validity_rate"] = (validity["validity_rate"] * 100).round(1)

    # Build a pivot for display
    pivot = validity.pivot(index="Method", columns="Dataset", values="validity_rate")
    pivot = pivot[["MNIST", "CIFAR-10"]]  # consistent ordering

    # Color-code cells
    def color_cell(val):
        if pd.isna(val):
            return ""
        if val >= 80:
            color = "#c8f7c5"
        elif val >= 50:
            color = "#fff3cd"
        else:
            color = "#fcd0cf"
        return f"background-color: {color}"

    st.dataframe(
        pivot.style.applymap(color_cell).format("{:.1f}%"),
        use_container_width=True,
    )

    st.subheader("Plausibility distributions")
    col_a, col_b = st.columns(2)

    with col_a:
        st.markdown("**IM1** (lower = more plausible)")
        fig, ax = plt.subplots(figsize=(5, 3))
        for method in du.METHODS:
            vals = df[df["method"] == method]["IM1"].dropna()
            ax.hist(vals, bins=40, alpha=0.5, label=method, density=True)
        ax.set_xlabel("IM1")
        ax.set_ylabel("Density")
        ax.legend(fontsize=7)
        ax.set_xlim(0, 5)
        fig.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

    with col_b:
        st.markdown("**Implausibility score** (higher = less plausible)")
        fig, ax = plt.subplots(figsize=(5, 3))
        for method in du.METHODS:
            vals = df[df["method"] == method]["implausibility"].dropna()
            ax.hist(vals, bins=40, alpha=0.5, label=method, density=True)
        ax.set_xlabel("Implausibility")
        ax.set_ylabel("Density")
        ax.legend(fontsize=7)
        fig.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

    st.subheader("Timeout rates")
    timeout = df.groupby("method")["timeout"].mean().sort_values(ascending=False) * 100
    fig, ax = plt.subplots(figsize=(6, 2.5))
    bars = ax.barh(timeout.index, timeout.values, color=["#e07070" if v > 30 else "#70abe0" for v in timeout.values])
    ax.set_xlabel("Timeout %")
    ax.set_xlim(0, 100)
    for bar, val in zip(bars, timeout.values):
        ax.text(val + 1, bar.get_y() + bar.get_height() / 2, f"{val:.1f}%", va="center", fontsize=9)
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: Image Browser
# ═════════════════════════════════════════════════════════════════════════════
elif page == "Image Browser":
    st.title("Image Browser")
    st.markdown("Explore original images and their counterfactual explanations.")

    col1, col2, col3, col4 = st.columns([2, 2, 2, 2])

    with col1:
        dataset = st.selectbox("Dataset", ["MNIST", "CIFAR-10"])
    network = "mnist_output_100" if dataset == "MNIST" else "cifar_resnet8_output"

    sub = df[df["network"] == network]
    instance_ids = sorted(sub["image"].dropna().unique().astype(int).tolist())

    with col2:
        instance_id = st.selectbox("Instance ID", instance_ids)

    all_targets = sorted(sub[sub["image"] == instance_id]["target"].dropna().unique().astype(int).tolist())

    with col3:
        if dataset == "CIFAR-10":
            target_labels = [f"{t} ({CIFAR_LABELS.get(t,'?')})" for t in all_targets]
            target_label = st.selectbox("Target class", target_labels)
            target = int(target_label.split(" ")[0])
        else:
            target = st.selectbox("Target digit", all_targets)

    with col4:
        filter_valid = st.selectbox("Show methods", ["All", "Valid only", "Invalid only"])

    # Filters
    method_filter = None
    if filter_valid == "Valid only":
        method_filter = sub[(sub["image"] == instance_id) & (sub["target"] == target) & (sub["correctness"] == 1)]["method"].tolist()
    elif filter_valid == "Invalid only":
        method_filter = sub[(sub["image"] == instance_id) & (sub["target"] == target) & (sub["correctness"] == 0)]["method"].tolist()

    st.divider()

    is_mnist = dataset == "MNIST"

    # Show original image
    orig = du.load_image(network, instance_id, "original")
    orig_label = sub[sub["image"] == instance_id]["original_label"].iloc[0] if not sub[sub["image"] == instance_id].empty else "?"

    col_orig, col_info = st.columns([1, 3])
    with col_orig:
        if orig is not None:
            fig, ax = plt.subplots(figsize=(2, 2))
            ax.imshow(orig, cmap="gray" if is_mnist else None)
            ax.axis("off")
            orig_title = f"Original\nLabel: {int(orig_label)}"
            if not is_mnist:
                orig_title += f" ({CIFAR_LABELS.get(int(orig_label), '?')})"
            ax.set_title(orig_title, fontsize=9)
            fig.tight_layout()
            st.pyplot(fig)
            plt.close(fig)

    with col_info:
        st.markdown(f"**Instance:** {instance_id} &nbsp;|&nbsp; **Target:** {target}"
                    + (f" ({CIFAR_LABELS.get(target,'?')})" if not is_mnist else ""))
        row_orig = sub[sub["image"] == instance_id].iloc[0] if not sub[sub["image"] == instance_id].empty else {}
        if hasattr(row_orig, "to_dict"):
            st.markdown(f"Moran's I (original): `{row_orig.get('morans_i_original', 'N/A'):.4f}`")

    st.subheader("Counterfactual methods")

    methods_to_show = method_filter if method_filter is not None else du.METHODS
    n = len(methods_to_show)
    if n == 0:
        st.info("No CFs match the current filter.")
    else:
        cols = st.columns(n)
        for col, method in zip(cols, methods_to_show):
            with col:
                metrics = du.get_metric_row(network, instance_id, method, target)
                cf = du.load_image(network, instance_id, method, target)

                fig, ax = plt.subplots(figsize=(2.2, 2.2))
                if cf is not None:
                    ax.imshow(cf, cmap="gray" if is_mnist else None)
                else:
                    ax.text(0.5, 0.5, "N/A\n(timeout / missing)",
                            ha="center", va="center", transform=ax.transAxes,
                            fontsize=8, color="gray")
                    ax.set_facecolor("#f5f5f5")
                ax.axis("off")
                fig.tight_layout(pad=0.2)
                st.pyplot(fig)
                plt.close(fig)

                correctness = metrics.get("correctness", float("nan"))
                if correctness == 1:
                    st.success(f"**{method}** — Valid")
                elif correctness == 0:
                    st.error(f"**{method}** — Invalid")
                else:
                    st.warning(f"**{method}** — No data")

                im1 = metrics.get("IM1")
                im2 = metrics.get("IM2")
                implaus = metrics.get("implausibility")
                l1 = metrics.get("l1")

                metric_lines = []
                if im1 and not np.isnan(im1):
                    metric_lines.append(f"IM1: `{im1:.3f}`")
                if implaus and not np.isnan(implaus):
                    metric_lines.append(f"Implaus: `{implaus:.3f}`")
                if l1 and not np.isnan(l1):
                    metric_lines.append(f"L1: `{l1:.3f}`")
                st.markdown("  \n".join(metric_lines) if metric_lines else "*No metrics*")


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: Tension Cases
# ═════════════════════════════════════════════════════════════════════════════
elif page == "Tension Cases":
    st.title("Tension Cases")
    st.markdown(
        """
        These are the most interesting cases where **validity and plausibility disagree**.
        They are the heart of the research question.
        """
    )

    col1, col2, col3 = st.columns(3)
    with col1:
        ds_filter = st.selectbox("Dataset", ["Both", "MNIST", "CIFAR-10"])
    with col2:
        kind = st.selectbox(
            "Tension type",
            ["valid_implausible", "invalid_plausible"],
            format_func=lambda x: {
                "valid_implausible": "Valid but implausible (metric says OK, looks bad)",
                "invalid_plausible": "Invalid but high implausibility (metric says bad, looks plausible?)",
            }[x],
        )
    with col3:
        top_n = st.slider("Show top N", 5, 50, 15)

    network_filter = None
    if ds_filter == "MNIST":
        network_filter = "mnist_output_100"
    elif ds_filter == "CIFAR-10":
        network_filter = "cifar_resnet8_output"

    tension = du.find_tension_cases(network=network_filter, top_n=top_n, kind=kind)

    if tension.empty:
        st.info("No tension cases found with current filters.")
    else:
        display_cols = ["network", "image", "method", "target", "correctness", "IM1", "IM2", "implausibility", "l1"]
        display_cols = [c for c in display_cols if c in tension.columns]
        st.dataframe(tension[display_cols].round(4), use_container_width=True)

        st.subheader("Visualise a tension case")
        row_idx = st.number_input("Row index from table above (0-based)", 0, len(tension) - 1, 0)
        row = tension.iloc[int(row_idx)]

        network = row["network"]
        is_mnist = "mnist" in network
        instance_id = int(row["image"])
        target = int(row["target"])

        st.markdown(f"**{network}** — Instance {instance_id}, Target {target}"
                    + (f" ({CIFAR_LABELS.get(target,'?')})" if not is_mnist else ""))

        fig = du.make_grid_figure(network, instance_id, target)
        st.pyplot(fig)
        plt.close(fig)


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: Guess Mode
# ═════════════════════════════════════════════════════════════════════════════
elif page == "Guess Mode":
    st.title("Guess Mode — Human vs. Metric")
    st.markdown(
        """
        **Can you tell if a CF explanation is valid?**
        You will be shown a counterfactual image. Guess whether the model considers it valid
        (i.e., it crosses the decision boundary and produces the target class), then see the truth.
        Your responses are logged for the user study.
        """
    )

    # Session state for guess mode
    if "gm_row" not in st.session_state:
        st.session_state.gm_row = None
        st.session_state.gm_revealed = False
        st.session_state.gm_guess = None

    col_settings, _ = st.columns([2, 3])
    with col_settings:
        gm_dataset = st.selectbox("Dataset", ["Both", "MNIST", "CIFAR-10"], key="gm_dataset")
        gm_method = st.selectbox("Method filter", ["Any"] + du.METHODS, key="gm_method")

    def sample_new_case():
        sub = df[df["correctness"].notna()]
        if gm_dataset == "MNIST":
            sub = sub[sub["network"] == "mnist_output_100"]
        elif gm_dataset == "CIFAR-10":
            sub = sub[sub["network"] == "cifar_resnet8_output"]
        if gm_method != "Any":
            sub = sub[sub["method"] == gm_method]
        # Only rows where CF image actually exists (not timeout)
        sub = sub[sub["timeout"] != 1]
        if sub.empty:
            return None
        return sub.sample(1).iloc[0].to_dict()

    if st.button("New question", type="primary"):
        st.session_state.gm_row = sample_new_case()
        st.session_state.gm_revealed = False
        st.session_state.gm_guess = None

    row = st.session_state.gm_row

    if row is None:
        st.info("Press **New question** to start.")
    else:
        network = row["network"]
        is_mnist = "mnist" in network
        instance_id = int(row["image"])
        method = row["method"]
        target = int(row["target"])

        # Load images
        orig = du.load_image(network, instance_id, "original")
        cf = du.load_image(network, instance_id, method, target)

        if cf is None:
            st.warning("This CF image is blank (timeout). Press **New question**.")
        else:
            col_img, col_action = st.columns([2, 3])
            with col_img:
                fig, axes = plt.subplots(1, 2, figsize=(4, 2.5))
                axes[0].imshow(orig, cmap="gray" if is_mnist else None)
                orig_lbl = int(row["original_label"])
                orig_title = f"Original\n{orig_lbl}"
                if not is_mnist:
                    orig_title += f" ({CIFAR_LABELS.get(orig_lbl,'?')})"
                axes[0].set_title(orig_title, fontsize=9)
                axes[0].axis("off")

                axes[1].imshow(cf, cmap="gray" if is_mnist else None)
                tgt_title = f"CF — target {target}"
                if not is_mnist:
                    tgt_title += f"\n({CIFAR_LABELS.get(target,'?')})"
                axes[1].set_title(tgt_title, fontsize=9)
                axes[1].axis("off")
                fig.tight_layout()
                st.pyplot(fig)
                plt.close(fig)

                st.caption(f"Method: **{method}** | Dataset: {'MNIST' if is_mnist else 'CIFAR-10'}")

            with col_action:
                if not st.session_state.gm_revealed:
                    st.markdown("### Does this CF make the model predict the target class?")
                    guess_col1, guess_col2 = st.columns(2)
                    with guess_col1:
                        if st.button("Yes — I think it's valid", use_container_width=True):
                            st.session_state.gm_guess = 1
                            st.session_state.gm_revealed = True
                    with guess_col2:
                        if st.button("No — I think it's invalid", use_container_width=True):
                            st.session_state.gm_guess = 0
                            st.session_state.gm_revealed = True

                    confidence = st.slider("How confident are you? (1=not at all, 5=very)", 1, 5, 3, key="gm_conf")

                if st.session_state.gm_revealed:
                    actual = int(row["correctness"])
                    guess = st.session_state.gm_guess
                    correct_guess = guess == actual

                    if actual == 1:
                        st.success("**Truth: VALID** — the model does predict the target class.")
                    else:
                        st.error("**Truth: INVALID** — the model does NOT predict the target class.")

                    if correct_guess:
                        st.balloons()
                        st.markdown("You got it right!")
                    else:
                        st.markdown("Your intuition differed from the metric — that's exactly what this study explores!")

                    # Show metrics
                    with st.expander("See full metrics"):
                        metric_keys = ["IM1", "IM2", "implausibility", "l1", "l2", "linf",
                                       "morans_i_original", "morans_i_explanation", "optim_time"]
                        for k in metric_keys:
                            v = row.get(k)
                            if v is not None and not (isinstance(v, float) and np.isnan(v)):
                                st.markdown(f"**{k}**: `{v:.4f}`")

                    # Log the response
                    entry = {
                        "timestamp": time.time(),
                        "network": network,
                        "instance_id": instance_id,
                        "method": method,
                        "target": target,
                        "guess": guess,
                        "actual": actual,
                        "correct": correct_guess,
                        "confidence": st.session_state.get("gm_conf", None),
                        "IM1": row.get("IM1"),
                        "IM2": row.get("IM2"),
                        "implausibility": row.get("implausibility"),
                    }
                    save_guess(entry)

                    if st.button("Next question", type="primary"):
                        st.session_state.gm_row = sample_new_case()
                        st.session_state.gm_revealed = False
                        st.session_state.gm_guess = None
                        st.rerun()


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: Study Results
# ═════════════════════════════════════════════════════════════════════════════
elif page == "Study Results":
    st.title("User Study Results")
    st.markdown("Analysis of collected guess-mode responses.")

    guesses = load_guesses()
    if not guesses:
        st.info("No responses collected yet. Go to **Guess Mode** to start the study.")
    else:
        gdf = pd.DataFrame(guesses)
        gdf["timestamp"] = pd.to_datetime(gdf["timestamp"], unit="s")

        st.metric("Total responses", len(gdf))

        col1, col2 = st.columns(2)
        with col1:
            overall_acc = gdf["correct"].mean() * 100
            st.metric("Overall accuracy", f"{overall_acc:.1f}%")
        with col2:
            avg_conf = gdf["confidence"].mean() if "confidence" in gdf else float("nan")
            st.metric("Avg confidence", f"{avg_conf:.2f}" if not np.isnan(avg_conf) else "N/A")

        st.subheader("Accuracy by method")
        acc_method = gdf.groupby("method")["correct"].agg(["mean", "count"]).round(3)
        acc_method["mean"] = (acc_method["mean"] * 100).round(1)
        acc_method.columns = ["Accuracy %", "N responses"]
        st.dataframe(acc_method, use_container_width=True)

        st.subheader("Confusion: Human guess vs. Actual validity")
        from_valid = gdf[gdf["actual"] == 1]["guess"].value_counts()
        from_invalid = gdf[gdf["actual"] == 0]["guess"].value_counts()
        conf_df = pd.DataFrame({
            "Guessed Valid": [from_valid.get(1, 0), from_invalid.get(1, 0)],
            "Guessed Invalid": [from_valid.get(0, 0), from_invalid.get(0, 0)],
        }, index=["Actually Valid", "Actually Invalid"])
        st.dataframe(conf_df, use_container_width=True)

        st.subheader("Plausibility score vs. Correct guess")
        if "implausibility" in gdf.columns:
            fig, ax = plt.subplots(figsize=(6, 3))
            correct_impl = gdf[gdf["correct"] == True]["implausibility"].dropna()
            wrong_impl   = gdf[gdf["correct"] == False]["implausibility"].dropna()
            ax.hist(correct_impl, bins=20, alpha=0.6, label="Correct guess", color="#4caf50")
            ax.hist(wrong_impl,   bins=20, alpha=0.6, label="Wrong guess", color="#f44336")
            ax.set_xlabel("Implausibility score")
            ax.set_ylabel("Count")
            ax.legend()
            fig.tight_layout()
            st.pyplot(fig)
            plt.close(fig)

        with st.expander("Raw response log"):
            st.dataframe(gdf, use_container_width=True)

        if st.button("Download responses as CSV"):
            st.download_button(
                "Download CSV",
                gdf.to_csv(index=False),
                "guess_responses.csv",
                "text/csv",
            )
